export const groupParts = ["LEFTDOORF", "LEFTDOORB", "RIGHTDOORF", "RIGHTDOORB", "ROOF", "HOOD", "TRUNK", "WINDOWFRAMEL",
    "WINDOWFRAMER", "BUMPERF", "BUMPERB", "FENDERRF", "FENDERRB", "FENDERLF", "FENDERLB", "RUNBOARDL", "RUNBOARDR"]

export const groupPartsExtra = ["MIRRORL", "MIRRORR", "LIGHT", "RIN"]